title = "Zap!"
theme = "material"
baseUrl = "/"

disqusShortname = "zapcircle"

enableEmoji = true

pygmentsStyle = "tango"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClassic = false
pygmentsOptions = ["linenos=1"]

languageCode = "en-us"
defaultContentLanguage = "en"

copyright = "Â© 2022 Zap"

paginate = 10
paginatePath = "page"

[menu]
  [[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

  [[menu.main]]
    url = "/about"
    name = "About"
    weight = 2
  
  [[menu.main]]
    name = "100DaysOfCode"
    identifier = "100dof"
    weight = 3
    
    [[menu.main]]
      url = "/100-days-of-code"
      name = "100DaysOfCode"
      parent = "100dof"
      weight = 0
    [[menu.main]]
      url = "/100-days-of-code/rc"
      name = "RC"
      parent = "100dof"
      weight = 1
    [[menu.main]]
      url = "/100-days-of-code/mittalprince"
      name = "mittalprince"
      parent = "100dof"
      weight = 2
    [[menu.main]]
      url = "/100-days-of-code/geekychaser"
      name = "geekychaser"
      parent = "100dof"
      weight = 3
    [[menu.main]]
      url = "/100-days-of-code/rohit"
      name = "Rohit"
      parent = "100dof"
      weight = 4


[permalinks]
  posts = "/:filename/"

[params]
    url1 = "https://github.com/rishabhc32"
    name1 = "RC"
 
    url2 = "https://github.com/mittalprince"
    name2 = "mittalprince"

    url3 = "https://github.com/geekychaser"
    name3 = "geekychaser"

    url4 = "https://github.com/rohit3463"
    name4 = "Rohit"
